[platformio]
default_envs = m5stack-core2

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DAGENT_CONTROL_BOARD_CORE2=1

[env:m5stack-cores3]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
upload_speed = 1500000
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DESP32S3
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DAGENT_CONTROL_BOARD_CORES3=1
