[platformio]
default_envs = m5stack-core2

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson
